### ISSUE TITLE
no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by manilbajra** [gauravkatoch007/banana#6]
Skipped building banana due to the error:
Dependency "banana" has no shared framework schemes for any of the platforms: iOS

**Comment by gauravkatoch007** [comment]
Sure, I will check this. Creating a working example, hope I catch this error during that.

**Comment by gauravkatoch007** [comment]
Hi Manil,

Please check the working sample I have added just now. Also, I didn't encounter this error, let me know if you still facing issues, I am happy to help over weekends. Contact me gauravkatoch007 [AT] gmail [dot] com

**Comment by heisen273** [comment]
same thing happens to me:

MacBook-Air-Walter:UICollectionView anton$ carthage update
**\* Fetching banana
**\* Checking out banana at "1.0"
**\* xcodebuild output can be found in /var/folders/sw/hrlh1bqj55d_2x1y8d252l4r0000gn/T/carthage-xcodebuild.Svpjar.log
**\* Skipped building banana due to the error:
Dependency "banana" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/gauravkatoch007/banana/issues/new
